use crate::compute::SimulationComputeClock;
use crate::sync::SimulationEventBuffer;
use crate::time::SimulationTime;
use bevy::ecs::system::{Command, Deferred, SystemBuffer, SystemMeta, SystemParam};
use bevy::prelude::*;
use std::collections::BTreeMap;
use std::marker::PhantomData;

// TODO(@reuben-thomas): Use the Bevy `Command` and `Commands` queue instead of a blanket impl.
/// An instantaneous change on the state of a simulation [`bevy::prelude::World`] during a simulation.
pub trait DiscreteEvent: Send + Sync + 'static {
    /// Applies the event to the world.
    fn apply(self: Box<Self>, world: &mut World);

    /// Clones into a boxed object.
    fn clone_to_box(&self) -> Box<dyn DiscreteEvent>;

    /// A short, human-readable name identifying this kind of event.
    fn name(&self) -> &'static str;
}

impl<T> DiscreteEvent for T
where
    T: Command + Clone + Sync,
{
    fn apply(self: Box<Self>, world: &mut World) {
        Command::apply(*self, world)
    }

    fn clone_to_box(&self) -> Box<dyn DiscreteEvent> {
        Box::new(self.clone())
    }

    fn name(&self) -> &'static str {
        std::any::type_name::<T>()
    }
}

impl Clone for Box<dyn DiscreteEvent> {
    fn clone(&self) -> Self {
        self.clone_to_box()
    }
}

/// A resource holding candidate discrete events generated by systems.
#[derive(Resource, Default)]
pub struct CandidateDiscreteEvents(BTreeMap<SimulationTime, Vec<Box<dyn DiscreteEvent>>>);

impl CandidateDiscreteEvents {
    /// System to insert the time associated with the nearest upcoming event to the clock.
    pub fn update_clock_with_pending_time(
        mut events: ResMut<CandidateDiscreteEvents>,
        mut clock: ResMut<SimulationComputeClock>,
    ) {
        if let Some((&next_time, _)) = events.0.first_key_value() {
            events.0.retain(|&time, _| time == next_time);
            clock.insert_pending(next_time);
        }
    }

    /// Propose that a discrete event might occur at a time in the future.
    fn propose(
        &mut self,
        now: SimulationTime,
        event_time: SimulationTime,
        event: Box<dyn DiscreteEvent>,
    ) {
        if event_time < now {
            panic!(
                "Tried to schedule an event at time {event_time:?} \
                that is earlier than the current time {now:?} \
                and will never be executed.",
            );
        }
        self.0.entry(event_time).or_default().push(event);
    }

    /// System that executes the highest priority event at the current simulation time, discard all
    /// others.
    pub fn execute_highest_priority_current_event(world: &mut World) -> bool {
        let now = world.resource::<SimulationComputeClock>().now();
        let mut events = world.resource_mut::<CandidateDiscreteEvents>();
        let Some(event) = events
            .0
            .get(&now)
            .and_then(|events| events.first())
            .cloned()
        else {
            return false;
        };
        events.0.remove(&now);

        world
            .resource_mut::<SimulationEventBuffer>()
            .extend([event.clone()]);
        event.apply(world);
        true
    }

    fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

#[derive(SystemParam)]
pub struct DiscreteChangeWriter<'w, 's> {
    buffer: Deferred<'s, DiscreteEventBuffer>,
    clock: Res<'w, SimulationComputeClock>,
}

impl DiscreteChangeWriter<'_, '_> {
    pub fn write(&mut self, time: SimulationTime, event: impl DiscreteEvent) {
        self.buffer.queue(self.clock.now(), time, Box::new(event));
    }

    pub fn write_now(&mut self, event: impl DiscreteEvent) {
        self.write(self.clock.now(), event);
    }
}

#[derive(SystemParam)]
pub struct DiscreteComponentWriter<'w, 's, T: Component + Clone> {
    buffer: Deferred<'s, DiscreteEventBuffer>,
    clock: Res<'w, SimulationComputeClock>,
    _marker: PhantomData<T>,
}

impl<T: Component + Clone> DiscreteComponentWriter<'_, '_, T> {
    pub fn write(&mut self, time: SimulationTime, entity: Entity, value: T) {
        self.buffer.queue(
            self.clock.now(),
            time,
            Box::new(DiscreteComponentWrite { entity, value }),
        );
    }

    pub fn write_now(&mut self, entity: Entity, value: T) {
        self.write(self.clock.now(), entity, value);
    }
}

#[derive(Clone)]
struct DiscreteComponentWrite<T: Component + Clone> {
    entity: Entity,
    value: T,
}

// TODO(@reuben-thomas): Handle failures
impl<T: Component + Clone> Command for DiscreteComponentWrite<T> {
    fn apply(self, world: &mut World) {
        world.entity_mut(self.entity).insert(self.value);
    }
}

#[derive(SystemParam)]
pub struct DiscreteResourceWriter<'w, 's, R: Resource + Clone> {
    buffer: Deferred<'s, DiscreteEventBuffer>,
    clock: Res<'w, SimulationComputeClock>,
    _marker: PhantomData<R>,
}

impl<R: Resource + Clone> DiscreteResourceWriter<'_, '_, R> {
    pub fn write(&mut self, time: SimulationTime, value: R) {
        self.buffer.queue(
            self.clock.now(),
            time,
            Box::new(DiscreteResourceWrite { value }),
        );
    }

    pub fn write_now(&mut self, value: R) {
        self.write(self.clock.now(), value);
    }
}

#[derive(Clone)]
struct DiscreteResourceWrite<R: Resource + Clone> {
    value: R,
}

// TODO(@reuben-thomas): Fail if the resource already exists?
impl<R: Resource + Clone> Command for DiscreteResourceWrite<R> {
    fn apply(self, world: &mut World) {
        world.insert_resource(self.value);
    }
}

#[derive(Default)]
pub struct DiscreteEventBuffer(CandidateDiscreteEvents);

impl DiscreteEventBuffer {
    fn queue(&mut self, now: SimulationTime, time: SimulationTime, event: Box<dyn DiscreteEvent>) {
        self.0.propose(now, time, event);
    }
}

impl SystemBuffer for DiscreteEventBuffer {
    fn apply(&mut self, _system_meta: &SystemMeta, world: &mut World) {
        if self.0.is_empty() {
            return;
        }
        let buffered = std::mem::take(&mut self.0);
        let mut events = world.resource_mut::<CandidateDiscreteEvents>();
        for (time, buffered_events) in buffered.0 {
            events.0.entry(time).or_default().extend(buffered_events);
        }
    }
}
