use crate::compute::SimulationComputeClock;
use crate::sync::SimulationEventBuffer;
use crate::time::SimulationTime;
use bevy::ecs::system::{Command, Deferred, SystemBuffer, SystemMeta, SystemParam};
use bevy::prelude::*;
use std::collections::BTreeMap;
use std::fmt::Debug;
use std::marker::PhantomData;

/// [`bevy::prelude::World`] during a simulation.
pub trait DiscreteEvent: Command + Clone + Send + Sync + Debug + 'static {
    fn name() -> &'static str {
        std::any::type_name::<Self>()
    }
}

impl<T> DiscreteEvent for T where T: Command + Clone + Send + Sync + Debug + 'static {}

mod sealed {
    pub trait Sealed {}
}

// TODO(@reuben-thomas): Follow doc format specified in https://rust-lang.github.io/api-guidelines/future-proofing.html#sealed-traits-protect-against-downstream-implementations-c-sealed
impl<T: DiscreteEvent> sealed::Sealed for T {}

pub trait DynDiscreteEvent: sealed::Sealed + Debug + Send + Sync + 'static {
    fn apply(self: Box<Self>, world: &mut World);

    fn clone_to_box(&self) -> Box<dyn DynDiscreteEvent>;

    fn name(&self) -> &'static str;
}

impl<T: DiscreteEvent> DynDiscreteEvent for T {
    fn apply(self: Box<Self>, world: &mut World) {
        Command::apply(*self, world)
    }

    fn clone_to_box(&self) -> Box<dyn DynDiscreteEvent> {
        Box::new(self.clone())
    }

    fn name(&self) -> &'static str {
        <T as DiscreteEvent>::name()
    }
}

impl Clone for Box<dyn DynDiscreteEvent> {
    fn clone(&self) -> Self {
        self.clone_to_box()
    }
}

/// A resource holding candidate discrete events generated by systems.
#[derive(Resource, Default)]
pub struct CandidateDiscreteEvents(BTreeMap<SimulationTime, Vec<Box<dyn DynDiscreteEvent>>>);

impl CandidateDiscreteEvents {
    /// System to insert the time associated with the nearest upcoming event to
    /// the clock.
    pub fn update_clock_with_pending_time(
        mut events: ResMut<CandidateDiscreteEvents>,
        mut clock: ResMut<SimulationComputeClock>,
    ) {
        if let Some((&next_time, _)) = events.0.first_key_value() {
            events.0.retain(|&time, _| time == next_time);
            clock.insert_pending(next_time);
        }
    }

    /// Submit a discrete event that might occur at a time in the future.
    fn submit(
        &mut self,
        now: SimulationTime,
        event_time: SimulationTime,
        event: Box<dyn DynDiscreteEvent>,
    ) {
        if event_time < now {
            panic!(
                "Tried to schedule an event at time {event_time:?} \
                that is earlier than the current time {now:?} \
                and will never be executed.",
            );
        }
        self.0.entry(event_time).or_default().push(event);
    }

    /// System that executes the highest priority event at the current
    /// simulation time, discard all others.
    pub fn execute_highest_priority_current_event(world: &mut World) -> bool {
        let now = world.resource::<SimulationComputeClock>().now();
        let mut events = world.resource_mut::<CandidateDiscreteEvents>();
        let Some(event) = events
            .0
            .get(&now)
            .and_then(|events| events.first())
            .cloned()
        else {
            return false;
        };
        events.0.remove(&now);

        world
            .resource_mut::<SimulationEventBuffer>()
            .extend([event.clone()]);
        event.apply(world);
        true
    }

    fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

impl SystemBuffer for CandidateDiscreteEvents {
    fn apply(&mut self, _system_meta: &SystemMeta, world: &mut World) {
        if self.is_empty() {
            return;
        }
        let mut events = world.resource_mut::<CandidateDiscreteEvents>();
        while let Some((time, buffered)) = self.0.pop_first() {
            events.0.entry(time).or_default().extend(buffered);
        }
    }
}

/// Predicts [`DiscreteEvent`]s that may occur.
///
/// In most cases, you should use [`CandidateDiscreteComponentWriter`] or
/// [`CandidateDiscreteResourceWriter`] if you do not wish to implement a
/// [`DiscreteEvent`] struct.
#[derive(SystemParam)]
pub struct CandidateEventWriter<'w, 's> {
    buffer: Deferred<'s, CandidateDiscreteEvents>,
    clock: Res<'w, SimulationComputeClock>,
}

impl CandidateEventWriter<'_, '_> {
    pub fn predict(&mut self, time: SimulationTime, event: impl DiscreteEvent) {
        self.buffer.submit(self.clock.now(), time, Box::new(event));
    }

    pub fn predict_now(&mut self, event: impl DiscreteEvent) {
        self.predict(self.clock.now(), event);
    }
}

/// Predicts a component update as a discrete event.
#[derive(SystemParam)]
pub struct CandidateComponentEventWriter<'w, 's, T: Component + Clone + Debug> {
    buffer: Deferred<'s, CandidateDiscreteEvents>,
    clock: Res<'w, SimulationComputeClock>,
    _marker: PhantomData<T>,
}

impl<T: Component + Clone + Debug> CandidateComponentEventWriter<'_, '_, T> {
    pub fn predict(&mut self, time: SimulationTime, entity: Entity, value: T) {
        self.buffer.submit(
            self.clock.now(),
            time,
            Box::new(CandidateComponentWrite { entity, value }),
        );
    }

    pub fn predict_now(&mut self, entity: Entity, value: T) {
        self.predict(self.clock.now(), entity, value);
    }
}

#[derive(Clone, Debug)]
struct CandidateComponentWrite<T: Component + Clone + Debug> {
    entity: Entity,
    value: T,
}

// TODO(@reuben-thomas): Handle failures
impl<T: Component + Clone + Debug> Command for CandidateComponentWrite<T> {
    fn apply(self, world: &mut World) {
        world.entity_mut(self.entity).insert(self.value);
    }
}

/// Predicts a resource update as a discrete event.
#[derive(SystemParam)]
pub struct CandidateResourceEventWriter<'w, 's, R: Resource + Clone + Debug> {
    buffer: Deferred<'s, CandidateDiscreteEvents>,
    clock: Res<'w, SimulationComputeClock>,
    _marker: PhantomData<R>,
}

impl<R: Resource + Clone + Debug> CandidateResourceEventWriter<'_, '_, R> {
    pub fn predict(&mut self, time: SimulationTime, value: R) {
        self.buffer.submit(
            self.clock.now(),
            time,
            Box::new(CandidateResourceWrite { value }),
        );
    }

    pub fn predict_now(&mut self, value: R) {
        self.predict(self.clock.now(), value);
    }
}

#[derive(Clone, Debug)]
struct CandidateResourceWrite<R: Resource + Clone + Debug> {
    value: R,
}

// TODO(@reuben-thomas): Fail if the resource already exists?
impl<R: Resource + Clone + Debug> Command for CandidateResourceWrite<R> {
    fn apply(self, world: &mut World) {
        world.insert_resource(self.value);
    }
}
