[package]
name = "rmf_site_sim"
version = "0.0.2"
edition = "2024"
authors = ["Grey <mxgrey@intrinsic.ai>"]
description = "Discrete event simulation for the rmf_site_editor"
license = "Apache-2.0"
repository = "https://github.com/open-rmf/rmf_site"
readme = "README.md"
autoexamples = false

[[bin]]
name = "request_handling"
path = "examples/request_handling.rs"

[dependencies]
bevy = {workspace = true, features = ["dynamic_linking"]}

[dev-dependencies]
bevy-inspector-egui = {workspace = true}
