[package]
name = "rmf_site_sim"
version = "0.0.1"
edition = "2024"
authors = ["Grey <mxgrey@intrinsic.ai>"]
description = "Discrete event simulation for rmf_site_editor"
license = "Apache-2.0"
repository = "https://github.com/open-rmf/rmf_site"

[dependencies]
bevy = { workspace = true, features = ["dynamic_linking"] }
crossbeam-channel = { workspace = true }

[dev-dependencies]
rand = "0.8"
